# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *

import sys
from APservice import service
from APuser import user
from APdatabase import plan
from APdatabase import planedit



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        # MainWindow.setWindowFlags(QtCore.Qt.MSwindowsFixedSizeDialogHint)

        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setStyleSheet("#MainWindow{border-image:url(image/1.jpg)}")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 280, 58, 16))
        self.label.setObjectName("label")

        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(220, 320, 58, 16))
        self.label_2.setObjectName("label_2")

        self.usernameIN = QtWidgets.QLineEdit(self.centralwidget)
        self.usernameIN.setGeometry(QtCore.QRect(330, 280, 113, 21))
        self.usernameIN.setObjectName("usernameIN")

        self.passwodIN = QtWidgets.QLineEdit(self.centralwidget)
        self.passwodIN.setGeometry(QtCore.QRect(330, 320, 113, 21))
        self.passwodIN.setObjectName("passwodIN")

        self.zhuceBNT = QtWidgets.QPushButton(self.centralwidget)
        self.zhuceBNT.setGeometry(QtCore.QRect(300, 360, 100, 21))
        self.zhuceBNT.setObjectName("zhuceBNT")

        self.tuichuBNT = QtWidgets.QPushButton(self.centralwidget)
        self.tuichuBNT.setGeometry(QtCore.QRect(370, 390, 100, 32))
        self.tuichuBNT.setObjectName("tuichuBNT")

        self.dengluBNT = QtWidgets.QPushButton(self.centralwidget)
        self.dengluBNT.setGeometry(QtCore.QRect(220, 390, 100, 32))
        self.dengluBNT.setObjectName("dengluBNT")

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.label.setBuddy(self.usernameIN)
        self.label_2.setBuddy(self.passwodIN)


        self.retranslateUi(MainWindow)
        self.tuichuBNT.clicked.connect(MainWindow.close)#没问题了
        # QtCore.QMetaObject.connectSlotsByName(user.Ui_Form)#需要设计计划输入界面

        self.dengluBNT.clicked.connect(self.openMain)#没问题

        self.zhuceBNT.clicked.connect(self.zhuce)#可以了


    def zhuce(self,m):#可以了
        self.m = user.Ui_Form()
        self.m.show()




    def openMain(self):
        service.userName = self.usernameIN.text()  # 全局变量，记录用户名
        self.userPwd = self.passwodIN.text()  # 记录用户密码
        if service.userName != "" and self.userPwd != "":  # 判断用户名和密码不为空
            # 根据用户名和密码查询数据
            result = service.query("select * from tb_user where userName = %s and userPwd = %s", service.userName,
                                   self.userPwd)
            if len(result) > 0:  # 如果查询结果大于0，说明存在该用户，可以登录
                self.m = plan.Ui_MainWindow()  # 创建主窗体对象#需要设置计划输入的界面
                self.m.show()  # 显示主窗体
                MainWindow.hide()  # 隐藏当前的登录窗体
            else:
                self.usernameIN.setText("")  # 清空用户名文本
                self.passwodIN.setText("")  # 清空密码文本框
                QMessageBox.warning(None, '警告', '请输入正确的用户名和密码！', QMessageBox.Ok)
        else:
            QMessageBox.warning(None, '警告', '请输入用户名和密码！', QMessageBox.Ok)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "用户名："))
        self.label_2.setText(_translate("MainWindow", "密    码："))
        self.zhuceBNT.setText(_translate("MainWindow", "注册"))
        self.tuichuBNT.setText(_translate("MainWindow", "退出"))
        self.dengluBNT.setText(_translate("MainWindow", "登陆"))
if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow() # 创建窗体对象
    ui = Ui_MainWindow() # 创建PyQt5设计的窗体对象
    ui.setupUi(MainWindow) # 调用PyQt5窗体的方法对窗体对象进行初始化设置
    MainWindow.show() # 显示窗体
    sys.exit(app.exec_()) # 程序关闭时退出进程